export const WINDOW_RESIZE = "WINDOW_RESIZE";

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";

export const SYSTEM_MESSAGE = "SYSTEM_MESSAGE";
export const SYSTEM_MESSAGE_ERROR = "SYSTEM_MESSAGE_ERROR";

export const CHAT_RECORD_UPDATE = "CHAT_RECORD_UPDATE";
export const ONLINE_USER_UPDATE = "ONLINE_USER_UPDATE";
export const GROUP_UPDATE = "GROUP_UPDATE";
export const GROUP_DELETE = "GROUP_DELETE";
export const FRIEND_ADD = "FRIEND_ADD";
export const FRIEND_DELETE = "FRIEND_DELETE";
export const USER_PROFILE_UPDATE = "USER_PROFILE_UPDATE";
export const CHAT_ADD = "CHAT_ADD";
export const CHAT_GROUP_UPDATE = "CHAT_GROUP_UPDATE";
export const CHAT_USER_UPDATE = "CHAT_USER_UPDATE";
