export const WINDOW_RESIZE = "WINDOW_RESIZE";

export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";

export const SYSTEM_MESSAGE = "SYSTEM_MESSAGE";
export const SYSTEM_MESSAGE_ERROR = "SYSTEM_MESSAGE_ERROR";
